<?php
require_once __DIR__.'/../includes/functions.php'; require_admin(); ensure_product_media_table();

function product_slug(string $name): string { return trim(strtolower((string)preg_replace('/[^a-z0-9]+/i','-',$name)),'-'); }
function save_product_image(array $file, int $productId): bool {
    if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK || ($file['size']??0)>8*1024*1024) return false;
    $info=@getimagesize($file['tmp_name']); if(!$info) return false;
    $type=$info[2];$extension=match($type){IMAGETYPE_JPEG=>'jpg',IMAGETYPE_PNG=>'png',IMAGETYPE_WEBP=>'webp',default=>null};
    if(defined('IMAGETYPE_AVIF')&&$type===IMAGETYPE_AVIF)$extension='avif';if(!$extension)return false;
    $canConvert=function_exists('imagewebp')&&(!defined('IMAGETYPE_AVIF')||$type!==IMAGETYPE_AVIF||function_exists('imagecreatefromavif'));
    $name='product-'.bin2hex(random_bytes(10)).'.'.($canConvert?'webp':$extension);$path=UPLOAD_DIR.$name;$source=null;
    if($canConvert){$source=match($type){IMAGETYPE_JPEG=>@imagecreatefromjpeg($file['tmp_name']),IMAGETYPE_PNG=>@imagecreatefrompng($file['tmp_name']),IMAGETYPE_WEBP=>function_exists('imagecreatefromwebp')?@imagecreatefromwebp($file['tmp_name']):null,default=>null};if(defined('IMAGETYPE_AVIF')&&$type===IMAGETYPE_AVIF&&function_exists('imagecreatefromavif'))$source=@imagecreatefromavif($file['tmp_name']);}
    $saved=$source?imagewebp($source,$path,84):move_uploaded_file($file['tmp_name'],$path);if($source)imagedestroy($source);if(!$saved||!is_file($path))return false;
    $max=db()->prepare('SELECT COALESCE(MAX(sort_order),0) FROM product_images WHERE product_id=?');$max->execute([$productId]);$url=base('uploads/'.$name);
    db()->prepare('INSERT INTO product_images(product_id,image_url,sort_order) VALUES(?,?,?)')->execute([$productId,$url,(int)$max->fetchColumn()+1]);db()->prepare('UPDATE products SET image=COALESCE(NULLIF(image,\'\'),?) WHERE id=?')->execute([$url,$productId]);return true;
}
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf(); $action=$_POST['action']??'save';
 if($action==='review'){db()->prepare('INSERT INTO reviews(product_id,customer_name,rating,comment,status) VALUES(?,?,?,?,?)')->execute([(int)$_POST['product_id'],trim($_POST['customer_name']),max(1,min(5,(int)$_POST['rating'])),trim($_POST['comment']),'approved']);flash('success','تمت إضافة التقييم.');header('Location: '.base('admin/products.php?edit='.(int)$_POST['product_id']));exit;}
 if($action==='delete'&&!empty($_POST['id'])){db()->prepare('DELETE FROM products WHERE id=?')->execute([(int)$_POST['id']]);flash('success','تم حذف المنتج.');header('Location: '.base('admin/products.php'));exit;}
 $id=(int)($_POST['id']??0);$data=[trim($_POST['name']),trim($_POST['slug'])?:product_slug(trim($_POST['name'])),$_POST['category_id']?:null,trim($_POST['sku']),trim($_POST['barcode']),$_POST['price'],$_POST['old_price']?:null,max(0,(int)$_POST['stock']),trim($_POST['color']),trim($_POST['sizes']),trim($_POST['description']),$_POST['status'],isset($_POST['featured'])?1:0];
 try{if($id){db()->prepare('UPDATE products SET name=?,slug=?,category_id=?,sku=?,barcode=?,price=?,old_price=?,stock=?,color=?,sizes=?,description=?,status=?,featured=? WHERE id=?')->execute([...$data,$id]);}else{db()->prepare('INSERT INTO products(name,slug,category_id,sku,barcode,price,old_price,stock,color,sizes,description,status,featured) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($data);$id=(int)db()->lastInsertId();}
   foreach($_FILES['images']['tmp_name']??[] as $i=>$tmp)save_product_image(['tmp_name'=>$tmp,'error'=>$_FILES['images']['error'][$i],'size'=>$_FILES['images']['size'][$i]],$id); flash('success','تم حفظ المنتج والصور بنجاح.');
 }catch(Throwable $e){flash('error','تعذر الحفظ. تأكد من أن الرابط المختصر وSKU غير مكررين.');}
 header('Location: '.base('admin/products.php?edit='.$id));exit;
}
$edit=null;if(isset($_GET['edit'])){$s=db()->prepare('SELECT * FROM products WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}$cats=db()->query('SELECT * FROM categories WHERE status="active" ORDER BY sort_order,name')->fetchAll();$q=trim($_GET['q']??'');$s=db()->prepare('SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.name LIKE ? OR p.sku LIKE ? ORDER BY p.id DESC LIMIT 100');$s->execute(['%'.$q.'%','%'.$q.'%']);$rows=$s->fetchAll();$gallery=[];$reviews=[];if($edit){$s=db()->prepare('SELECT * FROM product_images WHERE product_id=? ORDER BY sort_order');$s->execute([$edit['id']]);$gallery=$s->fetchAll();$s=db()->prepare('SELECT * FROM reviews WHERE product_id=? ORDER BY id DESC');$s->execute([$edit['id']]);$reviews=$s->fetchAll();}$adminTitle=$edit?'تعديل المنتج':'إدارة المنتجات';include 'header.php';?>
<form class="form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>">
<div><label>اسم المنتج *</label><input name="name" required value="<?=e($edit['name']??'')?>"></div><div><label>الرابط المختصر</label><input name="slug" value="<?=e($edit['slug']??'')?>"></div><div><label>رمز المنتج SKU</label><input name="sku" required value="<?=e($edit['sku']??'')?>"></div><div><label>الباركود</label><input name="barcode" value="<?=e($edit['barcode']??'')?>"></div><div><label>التصنيف</label><select name="category_id"><option value="">اختر التصنيف</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=($edit['category_id']??'')==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div><div><label>السعر / السعر السابق</label><input type="number" name="price" required value="<?=e($edit['price']??'')?>"><input type="number" name="old_price" value="<?=e($edit['old_price']??'')?>" placeholder="السعر السابق"></div><div><label>المخزون</label><input type="number" name="stock" min="0" value="<?=e($edit['stock']??0)?>"></div><div><label>الألوان</label><input name="color" value="<?=e($edit['color']??'')?>" placeholder="مثال: أسود، بيج"></div><div><label>المقاسات</label><input name="sizes" value="<?=e($edit['sizes']??'')?>" placeholder="مثال: S, M, L"></div><div><label>الحالة</label><select name="status"><option value="active" <?=($edit['status']??'active')==='active'?'selected':''?>>متاح</option><option value="draft" <?=($edit['status']??'')==='draft'?'selected':''?>>مسودة</option><option value="archived" <?=($edit['status']??'')==='archived'?'selected':''?>>مؤرشف</option></select><label><input type="checkbox" name="featured" <?=!empty($edit['featured'])?'checked':''?>> منتج مميز</label></div><div class="full"><label>وصف المنتج</label><textarea name="description"><?=e($edit['description']??'')?></textarea></div><div class="full"><label>رفع صور المنتج</label><input type="file" name="images[]" accept="image/*" multiple data-image-picker><small class="muted">يمكنك اختيار عدة صور. تُحوّل تلقائياً إلى WebP مضغوط.</small></div><button class="button gold">حفظ المنتج</button></form>
<?php if($edit):?><div class="panel"><div class="panel-head"><h2>صور المنتج</h2><a class="button ghost" href="<?=base('admin/product-media.php?product='.$edit['id'])?>">إدارة وترتيب جميع الصور</a></div><?php if($gallery):?><div style="display:flex;gap:10px;flex-wrap:wrap"><?php foreach($gallery as $img):?><img src="<?=e($img['image_url'])?>" alt="" style="width:90px;height:110px;object-fit:cover;border-radius:8px"><?php endforeach;?></div><?php else:?><div class="empty">لم يتم رفع صور لهذا المنتج بعد.</div><?php endif;?></div><div class="panel"><h2>إضافة تقييم للمنتج</h2><form class="form" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="review"><input type="hidden" name="product_id" value="<?=$edit['id']?>"><div><label>اسم العميل</label><input name="customer_name" required></div><div><label>التقييم</label><select name="rating"><option value="5">5 نجوم</option><option value="4">4 نجوم</option><option value="3">3 نجوم</option><option value="2">نجمتان</option><option value="1">نجمة</option></select></div><div class="full"><label>التعليق</label><textarea name="comment" required></textarea></div><button class="button gold">إضافة التقييم</button></form><?php if($reviews):?><div class="table-wrap"><table class="table"><tr><th>العميل</th><th>التقييم</th><th>التعليق</th><th>الحالة</th></tr><?php foreach($reviews as $r):?><tr><td><?=e($r['customer_name'])?></td><td><?=str_repeat('★',$r['rating'])?></td><td><?=e($r['comment'])?></td><td><?=e($r['status'])?></td></tr><?php endforeach;?></table></div><?php endif;?></div><?php endif;?>
<div class="panel"><div class="panel-head"><h2>كل المنتجات</h2><form class="table-tools"><input class="search-input" name="q" value="<?=e($q)?>" placeholder="ابحث بالاسم أو SKU"><button class="button">بحث</button></form></div><div class="table-wrap"><table class="table"><tr><th>المنتج</th><th>التصنيف</th><th>السعر</th><th>المخزون</th><th>الحالة</th><th></th></tr><?php foreach($rows as $p):?><tr><td><?=e($p['name'])?><br><small><?=e($p['sku'])?></small></td><td><?=e($p['category'])?></td><td><?=money($p['price'])?></td><td><?=$p['stock']?></td><td><?=e($p['status'])?></td><td><a class="button" href="?edit=<?=$p['id']?>">تعديل</a><form class="inline" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$p['id']?>"><button name="action" value="delete" class="button red" data-confirm="هل تريد حذف المنتج؟">حذف</button></form></td></tr><?php endforeach;?></table></div></div><script>
document.querySelector('[data-image-picker]')?.addEventListener('change', function () {
  const box=document.querySelector('#selected-images') || document.createElement('div');
  box.id='selected-images'; box.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin-top:10px'; box.innerHTML='';
  [...this.files].forEach(file => { const image=document.createElement('img'); image.src=URL.createObjectURL(file); image.style.cssText='width:76px;height:92px;object-fit:cover;border-radius:7px;border:1px solid #e9e5de'; box.appendChild(image); });
  this.parentElement.appendChild(box);
});
</script><?php include 'footer.php'; ?>
