<?php
require_once __DIR__.'/../includes/functions.php'; require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$id=(int)($_POST['id']??0);$action=$_POST['action']??'';
 if($action==='delete') db()->prepare('DELETE FROM reviews WHERE id=?')->execute([$id]);
 else { $status=in_array($_POST['status']??'', ['pending','approved','rejected'],true)?$_POST['status']:'pending'; db()->prepare('UPDATE reviews SET status=?,admin_reply=?,replied_at=IF(?="",NULL,NOW()) WHERE id=?')->execute([$status,trim($_POST['admin_reply']??''),trim($_POST['admin_reply']??''),$id]); }
 flash('success','Review updated.'); header('Location: '.base('admin/reviews.php')); exit;
}
$q=trim($_GET['q']??'');$status=$_GET['status']??'';$where=[];$args=[];if($q!==''){$where[]='(r.customer_name LIKE ? OR r.comment LIKE ? OR p.name LIKE ?)';$args=array_fill(0,3,'%'.$q.'%');}if(in_array($status,['pending','approved','rejected'],true)){$where[]='r.status=?';$args[]=$status;}$sql='SELECT r.*,p.name product FROM reviews r JOIN products p ON p.id=r.product_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY r.id DESC';$st=db()->prepare($sql);$st->execute($args);$rows=$st->fetchAll();$adminTitle='Review moderation';include 'header.php';?>
<div class="panel"><div class="panel-head"><h2>Customer reviews</h2><form class="table-tools" method="get"><input class="search-input" name="q" value="<?=e($q)?>" placeholder="Search reviews"><select name="status"><option value="">All statuses</option><?php foreach(['pending','approved','rejected'] as $v):?><option value="<?=$v?>" <?=$status===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select><button class="button">Filter</button></form></div>
<?php if(!$rows):?><div class="empty">No reviews match this view.</div><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Customer</th><th>Rating</th><th>Review</th><th>Moderation</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['product'])?></td><td><?=e($r['customer_name'])?><br><small><?=e($r['created_at'])?></small></td><td><?=str_repeat('★',(int)$r['rating'])?></td><td><?=e($r['comment'])?><?php if($r['admin_reply']):?><br><small class="muted">Reply: <?=e($r['admin_reply'])?></small><?php endif;?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status"><?php foreach(['pending','approved','rejected'] as $v):?><option <?=$r['status']===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select><input name="admin_reply" value="<?=e($r['admin_reply'])?>" placeholder="Reply"><button class="button gold">Save</button><button name="action" value="delete" class="button red" data-confirm="Delete this review permanently?">Delete</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div><?php include 'footer.php'; ?>
