<?php
require_once __DIR__.'/../includes/functions.php';
$action=$_GET['action']??'';
if($action==='cart'){
 header('Content-Type: application/json');
 if($_SERVER['REQUEST_METHOD']!=='POST'||!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);echo json_encode(['ok'=>false]);exit;}
 $id=(int)$_POST['product_id'];$qty=max(1,min(10,(int)$_POST['qty']));$p=db()->prepare('SELECT id FROM products WHERE id=? AND status="active"');$p->execute([$id]);if(!$p->fetch()){echo json_encode(['ok'=>false]);exit;}
 $size=trim($_POST['size']??''); $color=trim($_POST['color']??'');
 $cartKey = $id . ($size ? '_'.$size : '') . ($color ? '_'.$color : '');
 if(isset($_SESSION['cart'][$cartKey])) {
    $_SESSION['cart'][$cartKey]['qty'] = min(10, $_SESSION['cart'][$cartKey]['qty'] + $qty);
 } else {
    $_SESSION['cart'][$cartKey]=['product_id'=>$id, 'qty'=>$qty, 'size'=>$size, 'color'=>$color];
 }
 if(!empty($_POST['event_id']))send_meta_capi_event('AddToCart',$_POST['event_id'],['content_ids'=>[$id],'content_type'=>'product']);echo json_encode(['ok'=>true,'count'=>cart_count()]);exit;
}
if($action==='update-cart'){check_csrf();$cartKey=$_POST['cart_key']??'';$qty=(int)$_POST['qty'];if($qty<1)unset($_SESSION['cart'][$cartKey]);else if(isset($_SESSION['cart'][$cartKey])) $_SESSION['cart'][$cartKey]['qty']=min(10,$qty);header('Location: '.base('cart.php'));exit;}
if($action!=='create'||$_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit;}
check_csrf();
// Rate limits and honeypots removed
$name=trim($_POST['full_name']??'');$phone=preg_replace('/\s+/','',$_POST['phone']??'');$wid=(int)($_POST['wilaya_id']??0);$cid=(int)($_POST['commune_id']??0);$address=trim($_POST['address']??'');$deliveryType=$_POST['delivery_type']??'home';if(!in_array($deliveryType,['office','home'],true))$deliveryType='home';
if(mb_strlen($name)<3||!preg_match('/^0[5-7][0-9]{8}$/',$phone)||!$wid||!$cid||mb_strlen($address)<5){flash('error','يرجى مراجعة بيانات التوصيل.');header('Location: '.base('checkout.php'));exit;}
$ip=get_real_ip();$fp=substr(hash('sha256',($_SERVER['HTTP_USER_AGENT']??'').($_SERVER['HTTP_ACCEPT_LANGUAGE']??'')),0,64);
// Blacklist check removed
$items=cart();
$product_ids = [];
foreach($items as $k=>$it) $product_ids[] = $it['product_id'] ?? (int)$k;
$products=get_products($product_ids);if(!$products){flash('error','حقيبتكِ فارغة.');header('Location: '.base('shop.php'));exit;}
$commune=db()->prepare('SELECT id FROM communes WHERE id=? AND wilaya_id=?');$commune->execute([$cid,$wid]);if(!$commune->fetch()){flash('error','البلدية المختارة لا تتبع الولاية.');header('Location: '.base('checkout.php'));exit;}
$subtotal=0;foreach($items as $k=>$it){$pid=$it['product_id']??(int)$k;if(!isset($products[$pid])||$products[$pid]['stock']<$it['qty']){flash('error','إحدى القطع لم تعد متاحة بالكمية المطلوبة.');header('Location: '.base('cart.php'));exit;}$subtotal+=$products[$pid]['price']*$it['qty'];}
$ship=db()->prepare('SELECT office_shipping_price,home_shipping_price FROM wilayas WHERE id=?');$ship->execute([$wid]);$prices=$ship->fetch()?:[];$shipping=(float)($deliveryType==='office'?($prices['office_shipping_price']??0):($prices['home_shipping_price']??0));$pdo=db();
$promoCode = strtoupper(trim($_POST['promo_code'] ?? '')); $discountAmount = 0; if ($promoCode) { $promo = $pdo->prepare("SELECT * FROM promo_codes WHERE code=? AND status='active'"); $promo->execute([$promoCode]); $promoData = $promo->fetch(); if ($promoData && (!$promoData['expires_at'] || strtotime($promoData['expires_at']) >= time()) && (!$promoData['usage_limit'] || $promoData['used_count'] < $promoData['usage_limit'])) { $totalBeforeDiscount = $subtotal + $shipping; if ($promoData['discount_type'] === 'percentage') { $discountAmount = $totalBeforeDiscount * ($promoData['discount_value'] / 100); } else { $discountAmount = (float)$promoData['discount_value']; } } else { $promoCode = null; } } $finalTotal = max(0, $subtotal + $shipping - $discountAmount);
try{$pdo->beginTransaction();$customer=$pdo->prepare('SELECT id,is_blacklisted FROM customers WHERE phone=? LIMIT 1');$customer->execute([$phone]);$existing=$customer->fetch();if($existing&&$existing['is_blacklisted']){} /*throw new RuntimeException('blacklisted');*/ $customerId=$existing['id']??0;if(!$customerId){$pdo->prepare('INSERT INTO customers(full_name,phone,phone2,email) VALUES(?,?,?,?)')->execute([$name,$phone,trim($_POST['phone2']??''),'']);$customerId=(int)$pdo->lastInsertId();}$dup=$pdo->prepare('SELECT COUNT(*) FROM orders WHERE phone=? AND created_at>DATE_SUB(NOW(),INTERVAL 15 MINUTE)');$dup->execute([$phone]);if((int)$dup->fetchColumn()>0){} /*throw new RuntimeException('duplicate');*/ if(!is_admin()){$ipDup=$pdo->prepare('SELECT COUNT(*) FROM orders WHERE ip_address=? AND created_at>DATE_SUB(NOW(),INTERVAL 30 MINUTE)');$ipDup->execute([$ip]);if((int)$ipDup->fetchColumn()>0){} /*throw new RuntimeException('ip_duplicate');*/}$number='ALN-'.date('Y').'-'.strtoupper(bin2hex(random_bytes(3)));$finalNotes=trim($_POST['notes']??'')."\n[توصيل: ".($deliveryType==='office'?'مكتب':'منزل')."]";$stmt=$pdo->prepare('INSERT INTO orders(order_number,customer_id,full_name,phone,phone2,wilaya_id,commune_id,address,notes,subtotal,shipping_cost,promo_code,discount_amount,total,status,ip_address,user_agent,fingerprint,risk_score) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?, "received",?,?,?,?)');$stmt->execute([$number,$customerId,$name,$phone,trim($_POST['phone2']??''),$wid,$cid,$address,$finalNotes,$subtotal,$shipping,$promoCode,$discountAmount,$finalTotal,$ip,$_SERVER['HTTP_USER_AGENT']??'',$fp,0]);$orderId=(int)$pdo->lastInsertId();$line=$pdo->prepare('INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price,total,size,color) VALUES(?,?,?,?,?,?,?,?)');foreach($items as $k=>$it){$pid=$it['product_id']??(int)$k;$p=$products[$pid];$line->execute([$orderId,$pid,$p['name'],$it['qty'],$p['price'],$p['price']*$it['qty'],$it['size']??null,$it['color']??null]);$pdo->prepare('UPDATE products SET stock=stock-?,sales_count=sales_count+? WHERE id=?')->execute([$it['qty'],$it['qty'],$pid]);}$pdo->prepare('UPDATE customers SET total_orders=total_orders+1,total_spent=total_spent+? WHERE id=?')->execute([$finalTotal,$customerId]); if($promoCode) $pdo->prepare('UPDATE promo_codes SET used_count=used_count+1 WHERE code=?')->execute([$promoCode]); $pdo->commit();$_SESSION['cart']=[];log_activity('order_created',$number);send_meta_capi_event('Purchase',$number,['currency'=>'DZD','value'=>(float)$finalTotal],['ph'=>$phone]);header('Location: '.base('order-success.php?order='.urlencode($number)));}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();log_activity('order_error',$e->getMessage());flash('error','تفاصيل الخطأ: '.$e->getMessage());header('Location: '.base('checkout.php'));}
